### ISSUE TITLE
nullary error() behavior different from stock lua

### ISSUE THREAD

**Issue by ferronn-dev** [Meorawr/tainted-lua#4]
```sh
$ lua -e 'print(1); error(); print(2)'
1
$ elune/build/linux/bin/Release/lua5.1 -e 'print(1); error(); print(2)'
1
elune/build/linux/bin/Release/lua5.1: (error object is a nil value)
stack traceback:
        [C]: in function 'error'
        (command line):1: in main chunk
        [C]: in ?
```

Found through the busted Lua unittest framework, which [uses][1] `error()` on exit.

[1]: https://github.com/lunarmodules/busted/blob/master/busted/compatibility.lua#L38

**Comment by Meorawr** [comment]
What busted is doing is weird and isn't even supported in newer Lua versions anyway; 5.3 onwards all raise this same error. Not going to fix this unless there's an extremely compelling reason since this has a impact on how the default global error handler will process `nil` errors and breaks other invariants elsewhere.
